version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./qna-backend:/app/qna-backend
      - ./qna-frontend:/app/qna-frontend
    environment:
      - FLASK_ENV=development